# Generated by Django 5.0 on 2025-04-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='edrpou',
            field=models.IntegerField(blank=True, help_text='Код ЄДРПОУ особи', null=True, unique=True, verbose_name='ЄДРПОУ'),
        ),
    ]
