# Generated by Django 5.0 on 2025-04-26 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0005_comment_created_at_comment_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='annual_tax',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Сума сплачених податків за рік', max_digits=15, null=True, verbose_name='Щорічні податки (₴)'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='avg_monthly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Середній дохід за місяць', max_digits=15, null=True, verbose_name='Ср. місячний дохід (₴)'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='destruction_date',
            field=models.DateField(blank=True, help_text='Дата руйнуввання підприємства', null=True, verbose_name='Дата руйнуввання'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='direct_loss_est',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Оцінка прямих збитків від війни', max_digits=15, null=True, verbose_name='Прямі збитки (₴)'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='edrpou',
            field=models.CharField(blank=True, help_text='Код ЄДРПОУ підприємства', max_length=10, null=True, unique=True, verbose_name='ЄДРПОУ'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='employees',
            field=models.IntegerField(blank=True, help_text='Кількість працівників', null=True, verbose_name='Працівники'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='indirect_loss_est',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Оцінка непрямих збитків від війни', max_digits=15, null=True, verbose_name='Непрямі збитки (₴)'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='premises_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Площа виробничих та офісних приміщень', max_digits=10, null=True, verbose_name='Площа (кв.м)'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='status',
            field=models.CharField(choices=[('active', 'Активне'), ('closed', 'Закрите'), ('damaged', 'Пошкоджене')], default='active', help_text='Стан підприємства: активне, закрите чи пошкоджене', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='owner',
            field=models.ForeignKey(help_text='User associated with the progress', on_delete=django.db.models.deletion.CASCADE, related_name='establishments', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
