# Generated by Django 5.0 on 2025-04-26 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establishments', '0006_establishment_annual_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='active',
            field=models.BooleanField(blank=True, default=False, help_text='Is the establishment active?', null=True, verbose_name='Active'),
        ),
    ]
